### PR TITLE
Feature/activate plugin

### PR DESCRIPTION
**Pull request by Ippey**
Related #6 .
I added function i_activate_the_plugin.
This methods always activate plugin regardless whether plugin is activated.

### CODE REVIEW

**Comment by miya0001** [comment]
@Ippey Thanks!

Could you add checking that is the pugins activated like following?
https://github.com/vccw-team/wordpress-extension/blob/master/src/Context/WordPressContext.php#L63-L81

It will always fail on production site because:

* The use case of this test is ensure the plugin is activated. In many case, the plugin is already activated.
* It will always fail after the test for second time.

**Comment by Ippey** [comment]
I will add checking. I ask a question.
If the plugin is already activated, the check result is...
- [ ] Invalid, throw exception
- [x] Valid, do nothing.(test is passed)

**Comment by miya0001** [comment]
Thanks!
Also, please add the check after activation.
And it should throw an exception.

**Comment by Ippey** [comment]
Add checking after activation, using "the_plugin_should_be" method.

**Comment by miya0001** [comment]
@Ippey 
Thanks! I'll resolve conflicts and merge into `master`.

**Pull request merged**
